"""v1_template slideshow generator.

Spec Dump 1 approach: deterministic, fixed slide-type set, no configuration surface.
Reads the theme packet, emits a .pptx with a small fixed sequence of slide types.
"""
from __future__ import annotations

from pathlib import Path
from typing import Optional

from pptx import Presentation
from pptx.util import Inches, Pt
from pptx.dml.color import RGBColor
from pptx.enum.text import PP_ALIGN

from ...packet import build_packet
from ...paths import theme_dir

SLIDE_W = Inches(13.333)
SLIDE_H = Inches(7.5)


def build(slug: str, *, out_path: Optional[Path] = None) -> Path:
    packet = build_packet(slug)
    target = out_path or (theme_dir(slug) / "out" / f"{slug}.v1.pptx")
    target.parent.mkdir(parents=True, exist_ok=True)

    prs = Presentation()
    prs.slide_width = SLIDE_W
    prs.slide_height = SLIDE_H

    _title_slide(prs, packet)
    _thesis_slide(prs, packet)

    for card in packet["exemplars"]:
        _card_spotlight(prs, card, label="EXEMPLAR")
    for card in packet["included"]:
        _card_spotlight(prs, card, label="")

    if packet["uncertain"]:
        _grid_slide(prs, packet["uncertain"], title="Uncertain — needs review")

    _citation_slide(prs, packet)

    prs.save(str(target))
    return target


# ---------- slide helpers ----------

def _add_blank(prs: Presentation):
    return prs.slides.add_slide(prs.slide_layouts[6])  # blank layout


def _add_text(slide, text: str, *, left, top, width, height, size=18, bold=False, align=PP_ALIGN.LEFT, color=None):
    tx = slide.shapes.add_textbox(left, top, width, height)
    tf = tx.text_frame
    tf.word_wrap = True
    p = tf.paragraphs[0]
    p.alignment = align
    run = p.add_run()
    run.text = text
    run.font.size = Pt(size)
    run.font.bold = bold
    if color is not None:
        run.font.color.rgb = color
    return tx


def _title_slide(prs, packet):
    slide = _add_blank(prs)
    t = packet["theme"]
    _add_text(
        slide,
        t["canonical_name"],
        left=Inches(0.7), top=Inches(2.6), width=Inches(12), height=Inches(1.6),
        size=54, bold=True, align=PP_ALIGN.CENTER,
    )
    sub = t["short_description"] or "A thematic survey of Magic cards"
    _add_text(
        slide, sub,
        left=Inches(0.7), top=Inches(4.3), width=Inches(12), height=Inches(0.8),
        size=22, align=PP_ALIGN.CENTER, color=RGBColor(0x55, 0x55, 0x55),
    )
    _add_text(
        slide, packet["generated_at"],
        left=Inches(0.7), top=Inches(7.0), width=Inches(12), height=Inches(0.4),
        size=10, align=PP_ALIGN.CENTER, color=RGBColor(0x99, 0x99, 0x99),
    )


def _thesis_slide(prs, packet):
    slide = _add_blank(prs)
    c = packet["counts"]
    _add_text(
        slide, "Scope",
        left=Inches(0.7), top=Inches(0.5), width=Inches(12), height=Inches(0.7),
        size=36, bold=True,
    )
    body = (
        f"This deck surveys the {c['exemplar']} exemplar and {c['include']} included cards "
        f"linked to the theme. {c['uncertain']} additional candidates are flagged for review. "
        f"Generated by {packet['generator']}."
    )
    _add_text(
        slide, body,
        left=Inches(0.7), top=Inches(1.4), width=Inches(12), height=Inches(2),
        size=20,
    )


def _card_spotlight(prs, card: dict, *, label: str = ""):
    slide = _add_blank(prs)
    if card.get("image_path"):
        try:
            slide.shapes.add_picture(card["image_path"], Inches(0.5), Inches(0.7), height=Inches(6.0))
        except (FileNotFoundError, OSError):
            pass

    _add_text(
        slide, card["card_name"],
        left=Inches(5.5), top=Inches(0.7), width=Inches(7.3), height=Inches(0.8),
        size=32, bold=True,
    )
    _add_text(
        slide, f"{card.get('type_line', '')}   {card.get('mana_cost', '')}",
        left=Inches(5.5), top=Inches(1.6), width=Inches(7.3), height=Inches(0.5),
        size=16, color=RGBColor(0x55, 0x55, 0x55),
    )
    if label:
        _add_text(
            slide, label,
            left=Inches(5.5), top=Inches(2.2), width=Inches(2), height=Inches(0.4),
            size=12, bold=True, color=RGBColor(0xB0, 0x00, 0x00),
        )
    body_lines = []
    if card.get("link_reason"):
        body_lines.append(f"Why: {card['link_reason']}")
    if card.get("note"):
        body_lines.append(f"Note: {card['note']}")
    body_lines.append(f"Source: Scryfall  ·  conf {card['confidence']:.2f}  ·  {card['link_type']}")
    _add_text(
        slide, "\n".join(body_lines),
        left=Inches(5.5), top=Inches(2.8), width=Inches(7.3), height=Inches(4),
        size=16,
    )


def _grid_slide(prs, cards: list[dict], *, title: str):
    slide = _add_blank(prs)
    _add_text(
        slide, title,
        left=Inches(0.5), top=Inches(0.3), width=Inches(12), height=Inches(0.6),
        size=28, bold=True,
    )
    cols = 4
    cell_w = (SLIDE_W - Inches(1)) / cols
    cell_h = Inches(1.6)
    for i, card in enumerate(cards[:16]):
        r, c = divmod(i, cols)
        left = Inches(0.5) + cell_w * c
        top = Inches(1.2) + cell_h * r
        _add_text(
            slide, card["card_name"],
            left=left, top=top, width=cell_w, height=Inches(0.5),
            size=14, bold=True,
        )
        _add_text(
            slide, card.get("type_line", ""),
            left=left, top=top + Inches(0.5), width=cell_w, height=Inches(1),
            size=10, color=RGBColor(0x66, 0x66, 0x66),
        )


def _citation_slide(prs, packet):
    slide = _add_blank(prs)
    _add_text(
        slide, "Sources",
        left=Inches(0.7), top=Inches(0.5), width=Inches(12), height=Inches(0.7),
        size=32, bold=True,
    )
    lines = [
        "Card data and images: Scryfall (https://scryfall.com)",
        "Card images and names © Wizards of the Coast",
        f"Theme review: local curation under MTGSLIDER ({packet['generator']})",
        f"Packet generated: {packet['generated_at']}",
    ]
    _add_text(
        slide, "\n".join(lines),
        left=Inches(0.7), top=Inches(1.5), width=Inches(12), height=Inches(5),
        size=16,
    )
