"""Static-site generator. Walks the repo and writes a browseable HTML site under site/.

Usage:
    python tools/build_site.py

Pages produced:
    site/index.html              — project overview + section links
    site/docs.html               — every .md in writing/ + root-level docs
    site/decks.html              — bulk_index entries, links to .pptx files
    site/historical_trips.html   — etymology / biography / tradition cards
    site/decklists.html          — famous decks ingested into the DB
    site/conversation.html       — per-query log archive
    site/code.html               — links to source files

No framework. Markdown is rendered with a tiny in-house converter (headings, paragraphs,
links, code fences, tables) so the site has zero npm dependencies. Aesthetic borrowed
from Claudiens/AFSTYLING.md (warm parchment / dark brown serif / burnt sienna).
"""
from __future__ import annotations

import csv
import html
import re
import shutil
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
SITE = ROOT / "site"

CSS = """
:root {
  --bg: #f5f0e8;
  --bg-card: #fff;
  --text: #2c2418;
  --text-muted: #6b5d4d;
  --accent: #8b4513;
  --accent-light: #d4a574;
  --border: #d4c5a9;
  --header-bg: #2c2418;
  --header-text: #f5f0e8;
}
* { box-sizing: border-box; }
body { background: var(--bg); color: var(--text); font-family: Georgia, "Times New Roman", serif; line-height: 1.7; margin: 0; }
header { background: var(--header-bg); color: var(--header-text); padding: 1.4rem 2rem; }
header h1 { margin: 0; font-size: 1.4rem; letter-spacing: 0.02em; }
header nav { margin-top: 0.6rem; }
header nav a { color: var(--accent-light); margin-right: 1.2rem; text-decoration: none; font-family: "Segoe UI", system-ui, sans-serif; font-size: 0.92rem; }
header nav a:hover { color: var(--header-text); }
main { max-width: 920px; margin: 2rem auto; padding: 0 1.5rem 4rem; }
main h1 { color: var(--accent); border-bottom: 2px solid var(--border); padding-bottom: 0.4rem; }
main h2 { color: var(--accent); margin-top: 2.2rem; }
main h3 { color: var(--text); margin-top: 1.5rem; }
a { color: var(--accent); }
a:hover { color: var(--text); }
code { background: var(--bg-card); padding: 0.1em 0.35em; border: 1px solid var(--border); border-radius: 3px; font-size: 0.92em; }
pre { background: var(--bg-card); border: 1px solid var(--border); padding: 1rem; overflow-x: auto; font-size: 0.9em; }
pre code { background: transparent; border: none; padding: 0; }
table { border-collapse: collapse; margin: 1rem 0; width: 100%; }
th, td { border: 1px solid var(--border); padding: 0.5rem 0.75rem; text-align: left; vertical-align: top; }
th { background: var(--accent-light); color: var(--text); font-family: "Segoe UI", system-ui, sans-serif; font-weight: 600; }
.card { background: var(--bg-card); border: 1px solid var(--border); padding: 1.2rem 1.5rem; margin: 1rem 0; border-radius: 4px; }
.card h3 { margin-top: 0; }
.muted { color: var(--text-muted); font-size: 0.9rem; }
.tag { display: inline-block; background: var(--accent-light); color: var(--text); padding: 0.1rem 0.5rem; border-radius: 3px; font-size: 0.78rem; font-family: "Segoe UI", system-ui, sans-serif; margin-right: 0.3rem; }
footer { color: var(--text-muted); font-size: 0.85rem; text-align: center; padding: 2rem 1rem; border-top: 1px solid var(--border); }
"""

NAV = [
    ("index.html", "Home"),
    ("docs.html", "Documentation"),
    ("historical_trips.html", "Historical trips"),
    ("decks.html", "Slideshows"),
    ("decklists.html", "Decklists"),
    ("conversation.html", "Conversation log"),
    ("code.html", "Code"),
]


def page(title: str, body_html: str) -> str:
    nav_html = " ".join(f'<a href="{href}">{label}</a>' for href, label in NAV)
    return f"""<!doctype html>
<html lang="en"><head><meta charset="utf-8">
<title>{html.escape(title)} · MTGSLIDER</title>
<meta name="viewport" content="width=device-width, initial-scale=1">
<link rel="stylesheet" href="style.css">
</head><body>
<header>
  <h1><a href="index.html" style="color:inherit;text-decoration:none">MTGSLIDER</a></h1>
  <nav>{nav_html}</nav>
</header>
<main>{body_html}</main>
<footer>Generated by tools/build_site.py · github.com/t3dy/MTGSLIDER</footer>
</body></html>"""


# ---------- tiny markdown renderer ----------

def md_to_html(text: str) -> str:
    """Cover the markdown subset used in this repo. Not a general-purpose converter."""
    out: list[str] = []
    lines = text.split("\n")
    i = 0
    in_code = False
    code_buf: list[str] = []
    table_buf: list[list[str]] = []

    def flush_table():
        nonlocal table_buf
        if not table_buf:
            return
        # First row = header, second = separator (skip), rest = data
        header = table_buf[0]
        data = table_buf[2:] if len(table_buf) >= 2 else []
        out.append("<table><thead><tr>")
        for c in header:
            out.append(f"<th>{render_inline(c.strip())}</th>")
        out.append("</tr></thead><tbody>")
        for row in data:
            out.append("<tr>")
            for c in row:
                out.append(f"<td>{render_inline(c.strip())}</td>")
            out.append("</tr>")
        out.append("</tbody></table>")
        table_buf = []

    while i < len(lines):
        line = lines[i]
        if line.startswith("```"):
            if in_code:
                out.append("<pre><code>" + html.escape("\n".join(code_buf)) + "</code></pre>")
                code_buf = []
                in_code = False
            else:
                flush_table()
                in_code = True
            i += 1
            continue
        if in_code:
            code_buf.append(line)
            i += 1
            continue
        if line.startswith("|") and "|" in line[1:]:
            cells = [c for c in line.strip("|").split("|")]
            table_buf.append(cells)
            i += 1
            continue
        flush_table()
        if line.startswith("# "):
            out.append(f"<h1>{render_inline(line[2:])}</h1>")
        elif line.startswith("## "):
            out.append(f"<h2>{render_inline(line[3:])}</h2>")
        elif line.startswith("### "):
            out.append(f"<h3>{render_inline(line[4:])}</h3>")
        elif line.startswith("#### "):
            out.append(f"<h4>{render_inline(line[5:])}</h4>")
        elif line.startswith("- ") or line.startswith("* "):
            out.append("<ul>")
            while i < len(lines) and (lines[i].startswith("- ") or lines[i].startswith("* ")):
                out.append(f"<li>{render_inline(lines[i][2:])}</li>")
                i += 1
            out.append("</ul>")
            continue
        elif re.match(r"^\d+\.\s+", line):
            out.append("<ol>")
            while i < len(lines) and re.match(r"^\d+\.\s+", lines[i]):
                out.append(f"<li>{render_inline(re.sub(r'^\d+\.\s+', '', lines[i]))}</li>")
                i += 1
            out.append("</ol>")
            continue
        elif line.startswith("> "):
            out.append(f"<blockquote>{render_inline(line[2:])}</blockquote>")
        elif line.strip() == "---":
            out.append("<hr>")
        elif line.strip() == "":
            pass
        else:
            out.append(f"<p>{render_inline(line)}</p>")
        i += 1
    flush_table()
    return "\n".join(out)


def render_inline(s: str) -> str:
    s = html.escape(s)
    # links [text](url)
    s = re.sub(r"\[([^\]]+)\]\(([^)]+)\)", r'<a href="\2">\1</a>', s)
    # bold **x**
    s = re.sub(r"\*\*([^*]+)\*\*", r"<strong>\1</strong>", s)
    # italic *x*
    s = re.sub(r"(?<!\*)\*([^*]+)\*(?!\*)", r"<em>\1</em>", s)
    # inline code `x`
    s = re.sub(r"`([^`]+)`", r"<code>\1</code>", s)
    return s


# ---------- collectors ----------

def md_files_in(d: Path, *, exclude_names=("README.md",)) -> list[Path]:
    if not d.exists():
        return []
    return sorted(p for p in d.rglob("*.md") if p.name not in exclude_names)


def collect_root_docs() -> list[Path]:
    return [
        ROOT / "README.md",
        ROOT / "REFRAME_NOTES.md",
        ROOT / "ROADMAP.md",
        ROOT / "PARKING_LOT.md",
    ]


# ---------- page builders ----------

def build_index() -> str:
    body = md_to_html((ROOT / "README.md").read_text(encoding="utf-8"))
    body += """
<h2>Sections</h2>
<div class="card"><h3><a href="docs.html">Documentation</a></h3>
<p>Project docs (README, REFRAME_NOTES, ROADMAP, PARKING_LOT) plus the writing layer
(Deckard plans, context-engineering recommendations, overlay integration analysis,
representative-themes copy).</p></div>
<div class="card"><h3><a href="historical_trips.html">Historical trips</a></h3>
<p>Etymology / biography / tradition research cards generated by the
<code>mtg-historical-trip</code> skill. Each card traces a magical term through its
source-language chain and into MTG's design vocabulary.</p></div>
<div class="card"><h3><a href="decks.html">Slideshows</a></h3>
<p>98 auto-generated .pptx decks from the bulk-generation run. Browse by theme,
download individual files.</p></div>
<div class="card"><h3><a href="decklists.html">Decklists</a></h3>
<p>Famous tournament decks ingested into the database, with cross-references to themes
and historical trips.</p></div>
<div class="card"><h3><a href="conversation.html">Conversation log</a></h3>
<p>Every user query in the originating session, with how it was interpreted, what was
built, and what was deferred.</p></div>
<div class="card"><h3><a href="code.html">Code</a></h3>
<p>Source tree: Scryfall service, image pipeline, theme service, packet exporter, two
slideshow backends, ingesters, bulk runner, tests.</p></div>
"""
    return body


def build_docs() -> str:
    body = ["<h1>Documentation</h1>"]
    body.append("<h2>Root docs</h2>")
    for p in collect_root_docs():
        if not p.exists():
            continue
        rel = p.name.replace(".md", "")
        body.append(f'<div class="card"><h3><a href="docs/{rel}.html">{html.escape(rel)}</a></h3>')
        # Extract first paragraph
        text = p.read_text(encoding="utf-8")
        first_para = next((ln for ln in text.split("\n\n") if ln.strip() and not ln.startswith("#") and not ln.startswith(">")), "").strip()
        if first_para:
            body.append(f"<p>{html.escape(first_para[:300])}{'...' if len(first_para) > 300 else ''}</p>")
        body.append("</div>")
    body.append("<h2>writing/</h2>")
    for p in md_files_in(ROOT / "writing", exclude_names=("README.md",)):
        rel_inside = p.relative_to(ROOT / "writing")
        out_name = "writing-" + str(rel_inside).replace("/", "-").replace("\\", "-").replace(".md", "")
        body.append(f'<div class="card"><a href="docs/{out_name}.html">{html.escape(str(rel_inside))}</a></div>')
    return "\n".join(body)


def build_doc_page(p: Path, title: str) -> str:
    return md_to_html(p.read_text(encoding="utf-8"))


def build_decks() -> str:
    body = ["<h1>Slideshows</h1>",
            "<p>Auto-generated decks from the 100-theme bulk run. Each row links to the source <code>.pptx</code> file in the repo.</p>"]
    csv_path = ROOT / "themes" / "bulk_index.csv"
    if not csv_path.exists():
        body.append("<p><em>bulk_index.csv not found.</em></p>")
        return "\n".join(body)
    rows = list(csv.DictReader(csv_path.open(encoding="utf-8")))
    body.append("<table><thead><tr><th>#</th><th>Theme</th><th>Backend</th><th>Style</th><th>Cards</th><th>Deck</th></tr></thead><tbody>")
    for r in rows:
        # Construct relative path for the pptx
        pptx_rel = Path(r["pptx_path"]).as_posix()
        # Use the path relative to the repo root if possible
        try:
            pptx_rel = Path(r["pptx_path"]).resolve().relative_to(ROOT).as_posix()
        except ValueError:
            pass
        # Link path is relative from site/index.html one level deeper isn't necessary since site/ is in root
        link = f"../{pptx_rel}"
        body.append(f"<tr><td>{html.escape(r['index'])}</td><td>{html.escape(r['name'])}</td><td>{html.escape(r['backend'])}</td><td>{html.escape(r['style'])}</td><td>{html.escape(r['staged'])}</td><td><a href='{html.escape(link)}'>open .pptx</a></td></tr>")
    body.append("</tbody></table>")
    return "\n".join(body)


def build_historical_trips() -> str:
    body = ["<h1>Historical trips</h1>",
            "<p>Etymology / biography / tradition cards. Each card is a research artifact tracing a magical term through its source-language chain and into MTG's vocabulary.</p>"]
    et_dir = ROOT / "writing" / "historical_trips" / "etymology"
    if et_dir.exists():
        body.append("<h2>Etymology</h2>")
        for p in sorted(et_dir.glob("*.md")):
            text = p.read_text(encoding="utf-8")
            # Pull title and summary from frontmatter quickly
            title = p.stem
            summary = ""
            confidence = "medium"
            in_fm = False
            for line in text.splitlines():
                if line.strip() == "---":
                    in_fm = not in_fm
                    if not in_fm:
                        break
                    continue
                if in_fm:
                    if line.startswith("title:"):
                        title = line.split(":", 1)[1].strip()
                    elif line.startswith("summary:"):
                        summary = line.split(":", 1)[1].strip()
                    elif line.startswith("confidence:"):
                        confidence = line.split(":", 1)[1].strip()
            out_name = f"trips-etymology-{p.stem}"
            body.append(f'<div class="card"><h3><a href="docs/{out_name}.html">{html.escape(title)}</a> <span class="tag">{html.escape(confidence)}</span></h3>')
            if summary:
                body.append(f"<p>{html.escape(summary)}</p>")
            body.append("</div>")
    return "\n".join(body)


def build_decklists() -> str:
    body = ["<h1>Decklists</h1>",
            "<p>Famous tournament decks ingested into the database. Each is annotated with archetype context, banlist history, and a link to the cross-query report.</p>"]
    dl_dir = ROOT / "decklists"
    if dl_dir.exists():
        for p in sorted(dl_dir.glob("*.md")):
            out_name = f"decklists-{p.stem}"
            body.append(f'<div class="card"><h3><a href="docs/{out_name}.html">{html.escape(p.stem)}</a></h3></div>')
    # Link to cross-query demo
    cq = ROOT / "writing" / "CROSS_QUERY_HOGAAK_DEMO.md"
    if cq.exists():
        body.append('<h2>Cross-query reports</h2>')
        body.append('<div class="card"><a href="docs/writing-CROSS_QUERY_HOGAAK_DEMO.html">Hogaak Bridgevine ∩ MTGSLIDER themes</a></div>')
    return "\n".join(body)


def build_conversation() -> str:
    body = ["<h1>Conversation log</h1>",
            "<p>Per-query record of the originating MTGSLIDER session. Each entry documents how a user query was interpreted, what was built, and what was deferred.</p>"]
    log_dir = ROOT / "conversation_log"
    if log_dir.exists():
        for p in sorted(log_dir.glob("Q*.md")):
            text = p.read_text(encoding="utf-8")
            first_h1 = next((ln[2:] for ln in text.splitlines() if ln.startswith("# ")), p.stem)
            out_name = f"conv-{p.stem}"
            body.append(f'<div class="card"><h3><a href="docs/{out_name}.html">{html.escape(first_h1)}</a></h3></div>')
    return "\n".join(body)


def build_code() -> str:
    body = ["<h1>Code</h1>",
            "<p>The repo at a glance — links open the source files on GitHub.</p>"]
    body.append("<h2>Core modules</h2><ul>")
    src_root = ROOT / "src" / "mtgslider"
    if src_root.exists():
        for p in sorted(src_root.rglob("*.py")):
            rel = p.relative_to(ROOT).as_posix()
            body.append(f'<li><a href="https://github.com/t3dy/MTGSLIDER/blob/main/{rel}"><code>{html.escape(rel)}</code></a></li>')
    body.append("</ul>")
    body.append("<h2>Tools</h2><ul>")
    tools_root = ROOT / "tools"
    if tools_root.exists():
        for p in sorted(tools_root.glob("*.py")):
            rel = p.relative_to(ROOT).as_posix()
            body.append(f'<li><a href="https://github.com/t3dy/MTGSLIDER/blob/main/{rel}"><code>{html.escape(rel)}</code></a></li>')
    body.append("</ul>")
    body.append("<h2>Tests</h2><ul>")
    tests_root = ROOT / "tests"
    if tests_root.exists():
        for p in sorted(tests_root.glob("*.py")):
            rel = p.relative_to(ROOT).as_posix()
            body.append(f'<li><a href="https://github.com/t3dy/MTGSLIDER/blob/main/{rel}"><code>{html.escape(rel)}</code></a></li>')
    body.append("</ul>")
    return "\n".join(body)


# ---------- main ----------

def main() -> int:
    if SITE.exists():
        shutil.rmtree(SITE)
    SITE.mkdir(parents=True)
    (SITE / "docs").mkdir(parents=True, exist_ok=True)
    (SITE / "style.css").write_text(CSS, encoding="utf-8")

    # Top-level pages
    (SITE / "index.html").write_text(page("Home", build_index()), encoding="utf-8")
    (SITE / "docs.html").write_text(page("Documentation", build_docs()), encoding="utf-8")
    (SITE / "historical_trips.html").write_text(page("Historical trips", build_historical_trips()), encoding="utf-8")
    (SITE / "decks.html").write_text(page("Slideshows", build_decks()), encoding="utf-8")
    (SITE / "decklists.html").write_text(page("Decklists", build_decklists()), encoding="utf-8")
    (SITE / "conversation.html").write_text(page("Conversation log", build_conversation()), encoding="utf-8")
    (SITE / "code.html").write_text(page("Code", build_code()), encoding="utf-8")

    # Doc pages — every md file gets its own rendered html page
    n_doc_pages = 0
    for p in collect_root_docs():
        if not p.exists():
            continue
        rel = p.stem
        (SITE / "docs" / f"{rel}.html").write_text(
            page(p.stem, build_doc_page(p, p.stem)), encoding="utf-8")
        n_doc_pages += 1
    for p in md_files_in(ROOT / "writing"):
        rel = p.relative_to(ROOT / "writing")
        out_name = "writing-" + str(rel).replace("/", "-").replace("\\", "-").replace(".md", "")
        (SITE / "docs" / f"{out_name}.html").write_text(
            page(p.stem, build_doc_page(p, p.stem)), encoding="utf-8")
        n_doc_pages += 1
    for p in (ROOT / "writing" / "historical_trips" / "etymology").glob("*.md"):
        out_name = f"trips-etymology-{p.stem}"
        (SITE / "docs" / f"{out_name}.html").write_text(
            page(p.stem, build_doc_page(p, p.stem)), encoding="utf-8")
        n_doc_pages += 1
    for p in (ROOT / "decklists").glob("*.md"):
        out_name = f"decklists-{p.stem}"
        (SITE / "docs" / f"{out_name}.html").write_text(
            page(p.stem, build_doc_page(p, p.stem)), encoding="utf-8")
        n_doc_pages += 1
    for p in (ROOT / "conversation_log").glob("Q*.md"):
        out_name = f"conv-{p.stem}"
        (SITE / "docs" / f"{out_name}.html").write_text(
            page(p.stem, build_doc_page(p, p.stem)), encoding="utf-8")
        n_doc_pages += 1

    print(f"site/ generated. doc pages={n_doc_pages}. open site/index.html in a browser.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
